import os
import requests
import time
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

TOKEN = os.getenv("GITHUB_TOKEN")
OWNER = "KataDavidXD"
REPO = "GithubAutoLark"
BASE_URL = f"https://api.github.com/repos/{OWNER}/{REPO}"
HEADERS = {
    "Authorization": f"Bearer {TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28"
}

def log_result(operation, response):
    print(f"\n--- {operation} ---")
    print(f"Status Code: {response.status_code}")
    if response.status_code in [200, 201]:
        print("Success")
        return response.json()
    else:
        print(f"Failed: {response.text}")
        return None

def test_full_lifecycle():
    issue_number = None

    # 1. CREATE Issue
    print("\n1. Testing Create Issue...")
    create_data = {
        "title": "[TEST] Lifecycle Test Issue",
        "body": "Testing full lifecycle: Create -> Read -> Update -> Comment -> Close",
        "labels": ["test", "lifecycle"]
    }
    resp = requests.post(f"{BASE_URL}/issues", headers=HEADERS, json=create_data)
    result = log_result("Create Issue", resp)
    
    if result:
        issue_number = result['number']
        print(f"Created Issue #{issue_number}")
    else:
        return

    time.sleep(1)

    # 2. READ Issue
    print(f"\n2. Testing Read Issue #{issue_number}...")
    resp = requests.get(f"{BASE_URL}/issues/{issue_number}", headers=HEADERS)
    log_result("Read Issue", resp)

    time.sleep(1)

    # 3. UPDATE Issue (Edit body and add label)
    print(f"\n3. Testing Update Issue #{issue_number}...")
    update_data = {
        "body": "Testing full lifecycle: Create -> Read -> Update (UPDATED) -> Comment -> Close",
        "labels": ["test", "lifecycle", "updated"]
    }
    resp = requests.patch(f"{BASE_URL}/issues/{issue_number}", headers=HEADERS, json=update_data)
    log_result("Update Issue", resp)

    time.sleep(1)

    # 4. CREATE COMMENT
    print(f"\n4. Testing Create Comment on Issue #{issue_number}...")
    comment_data = {
        "body": "This is a test comment generated by the automation script."
    }
    resp = requests.post(f"{BASE_URL}/issues/{issue_number}/comments", headers=HEADERS, json=comment_data)
    log_result("Create Comment", resp)

    time.sleep(1)

    # 5. LIST COMMENTS
    print(f"\n5. Testing List Comments on Issue #{issue_number}...")
    resp = requests.get(f"{BASE_URL}/issues/{issue_number}/comments", headers=HEADERS)
    log_result("List Comments", resp)

    time.sleep(1)

    # 6. CLOSE Issue
    print(f"\n6. Testing Close Issue #{issue_number}...")
    close_data = {
        "state": "closed",
        "state_reason": "completed"
    }
    resp = requests.patch(f"{BASE_URL}/issues/{issue_number}", headers=HEADERS, json=close_data)
    log_result("Close Issue", resp)

if __name__ == "__main__":
    if not TOKEN:
        print("Error: GITHUB_TOKEN not found.")
    else:
        test_full_lifecycle()
